---
- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    shell: /sbin/nologin

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/node_exporter-1.6.1.linux-amd64

- name: Create symbolic link
  file:
    src: /opt/node_exporter-1.6.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    state: link

- name: Create node_exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Start and enable node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes